/**
 * АНГЛИЙСКИЙ ПЕРЕВОД
 *
 * Слева — фраза как она написана в игре, справа — перевод.
 * Порядок важен только для чтения человеком; игра ищет по точному совпадению.
 * Фразы, которых тут нет, останутся русскими — это нормально и заметно,
 * так видно, что ещё предстоит перевести.
 */
(function (global) {
  'use strict';
  const KM = global.KM;

  KM.I18N.add('en', {
    // ---------- главное меню ----------
    '▶ ИГРАТЬ': '▶ PLAY',
    '🛒 Магазин': '🛒 Shop',
    '🎰 Колесо и сундуки': '🎰 Wheel & chests',
    '🐾 Питомцы': '🐾 Pets',
    '⭐ Навыки': '⭐ Skills',
    '🐱 Коты': '🐱 Cats',
    '🎒 Сумка': '🎒 Bag',
    '⚙ Настройки': '⚙ Settings',
    '❔ Управление': '❔ Controls',
    '💾 Мои игры': '💾 My games',
    '🎮 Играть вдвоём': '🎮 Play together',
    '🌍 Сервера': '🌍 Servers',
    '🌐 Друзья': '🌐 Friends',
    '👤 Профиль': '👤 Profile',
    '🎨 Изменить профиль': '🎨 Edit profile',

    // ---------- общие кнопки ----------
    '← Назад': '← Back',
    'Назад': 'Back',
    'Отмена': 'Cancel',
    'Хорошо': 'OK',
    'Готово': 'Done',
    'Сохранить': 'Save',
    'Дальше': 'Next',
    'Войти': 'Log in',
    'Продолжить': 'Continue',
    '▶ Продолжить': '▶ Continue',
    'Выйти': 'Log out',
    'Удалить': 'Delete',
    'Убрать': 'Remove',
    'Закрыть': 'Close',
    'Купить': 'Buy',
    'Надеть': 'Equip',
    'Снять': 'Unequip',
    'Выбрать': 'Choose',
    'Играть': 'Play',
    'Ещё раз': 'Again',
    'В меню': 'Main menu',

    // ---------- экраны ----------
    'ЛОКАЦИИ': 'LOCATIONS',
    'МАГАЗИН': 'SHOP',
    'ПИТОМЦЫ': 'PETS',
    'НАВЫКИ': 'SKILLS',
    'КОТЫ': 'CATS',
    'СУМКА': 'BAG',
    'НАСТРОЙКИ': 'SETTINGS',
    'УПРАВЛЕНИЕ': 'CONTROLS',
    'ПАУЗА': 'PAUSED',
    'ПРОФИЛЬ': 'PROFILE',
    '👤 ПРОФИЛЬ': '👤 PROFILE',
    '🎨 МОЙ ПРОФИЛЬ': '🎨 MY PROFILE',
    '🌍 СЕРВЕРА': '🌍 SERVERS',
    '🌐 СЕРВЕР': '🌐 SERVER',
    '✉ ПЕРЕПИСКА': '✉ MESSAGES',
    '💾 МОИ ИГРЫ': '💾 MY GAMES',
    '🎰 КОЛЕСО И СУНДУКИ': '🎰 WHEEL & CHESTS',
    '🎮 ИГРАТЬ ВДВОЁМ': '🎮 PLAY TOGETHER',

    // ---------- игра ----------
    'Играть одному': 'Play alone',
    'Тихо, спокойно и без интернета. Обычная сложность.':
      'Quiet, calm and offline. Normal difficulty.',
    'ИГРАТЬ ВМЕСТЕ': 'PLAY TOGETHER',
    'ИЛИ САМОМУ': 'OR ON YOUR OWN',
    'ИЛИ': 'OR',
    'Игра на сервере': 'Playing on a server',
    'Дружная охота': 'Friendly hunt',
    'Красные против синих': 'Red vs blue',
    'Battle: один победитель': 'Battle: last cat standing',
    'Мирный': 'Peaceful',
    'Здоровье': 'Health',
    'Мана': 'Mana',
    'Уровень': 'Level',
    'Опыт': 'XP',
    'Монеты': 'Coins',
    'Пауза (Esc)': 'Pause (Esc)',
    'Сумка (I)': 'Bag (I)',
    'Кто играет': 'Who is playing',
    'Победа!': 'Victory!',
    'Кот сомлел': 'Your cat fainted',
    'ПОБЕДА': 'VICTORY',

    // ---------- сервера ----------
    'ОТКРЫТЫ ВСЕМ': 'OPEN TO EVERYONE',
    'СЕРВЕРА ИГРОКОВ': 'PLAYER SERVERS',
    '✨ Создать свой сервер': '✨ Create your own server',
    '✨ Открыть свой сервер здесь': '✨ Open your own server here',
    '▶ Играть здесь': '▶ Play here',
    '← К выбору режима': '← Back to modes',
    'ВАШ СОБСТВЕННЫЙ СЕРВЕР': 'YOUR OWN SERVER',
    'ВО ЧТО ИГРАЕМ': 'WHAT TO PLAY',
    'ГДЕ': 'WHERE',
    'КОГО ПУСКАТЬ': 'WHO CAN JOIN',
    'Всех подряд': 'Everyone',
    'Только друзей': 'Friends only',
    'По слову-ключу': 'With a password',
    'Название': 'Name',
    'Локация': 'Location',
    'Мест': 'Slots',
    'Подпись': 'Tagline',
    'Слово-ключ': 'Password',
    'В списке': 'In the list',
    '👁 Показывать всем': '👁 Show to everyone',
    '🙈 Не показывать': '🙈 Keep hidden',
    '🚀 Открыть сервер': '🚀 Open the server',
    '← К списку': '← Back to list',
    '👑 ВАШ СЕРВЕР': '👑 YOUR SERVER',
    '📨 Позвать': '📨 Invite',
    'уже тут': 'already here',
    'попросить уйти': 'ask them to leave',
    'в друзья': 'add as friend',
    '🏠 Поискать по всей домашней сети': '🏠 Search the whole home network',
    '🔌 Искать сервера': '🔌 Look for servers',
    '🔌 Попробовать снова': '🔌 Try again',
    'Вписать адрес вручную': 'Enter an address by hand',
    'Адрес': 'Address',
    'КУДА ИГРА СТУЧАЛАСЬ': 'WHERE THE GAME KNOCKED',
    '📂 ИГРА ОТКРЫТА ИЗ ФАЙЛА': '📂 GAME OPENED FROM A FILE',
    '🚀 Открыть с компьютера': '🚀 Open from the computer',
    '📋 Скопировать': '📋 Copy',
    '📱 ИГРАТЬ С ТЕЛЕФОНА': '📱 PLAY ON YOUR PHONE',
    'Домашний компьютер': 'Home computer',
    'Этот компьютер': 'This computer',
    'Этот сайт': 'This site',
    'Ваш адрес': 'Your address',
    'вы тут': 'you are here',

    // ---------- друзья и чат ----------
    '👥 Кто играет': '👥 Who is playing',
    '🐾 Друзья': '🐾 Friends',
    '➕ Добавить': '➕ Add',
    'ДРУЗЬЯ': 'FRIENDS',
    'ЗАЯВКИ В ДРУЗЬЯ': 'FRIEND REQUESTS',
    'Ник': 'Nickname',
    'Ник друга': "Friend's nickname",
    'ник друга': "friend's nickname",
    'начните вводить ник': 'start typing a nickname',
    '✔ Принять': '✔ Accept',
    '🐾 друг': '🐾 friend',
    '● в игре': '● in game',
    '📨 Позвать сюда': '📨 Invite here',
    '🌍 К нему': '🌍 Join them',
    'написать другу…': 'write to your friend…',
    'Тут пока пусто. Напишите первое письмо 🐾':
      'Nothing here yet. Write the first message 🐾',
    'не в игре': 'offline',
    'в игре': 'in game',
    '👥 КТО ИГРАЕТ': '👥 WHO IS PLAYING',

    // ---------- аккаунт ----------
    'АККАУНТ НА СЕРВЕРЕ': 'SERVER ACCOUNT',
    '🔑 Войти': '🔑 Log in',
    '✨ Завести новый': '✨ Create a new one',
    '✨ Создать новый аккаунт': '✨ Create a new account',
    '🐾 Завести аккаунт': '🐾 Create an account',
    '🔑 У меня уже есть': '🔑 I already have one',
    'Пароль': 'Password',
    'пароль': 'password',
    'ваш ник на сервере': 'your nickname on the server',
    'Имя': 'Name',
    'НА ЧЁМ ИГРАЕТЕ': 'WHAT DO YOU PLAY ON',
    'Компьютер': 'Computer',
    'Планшет': 'Tablet',
    'Телефон': 'Phone',
    'ДЕЙСТВИЯ': 'ACTIONS',
    '🔑 Сменить пароль': '🔑 Change password',
    '🔄 Другой аккаунт': '🔄 Switch account',
    '🚪 Выйти из аккаунта': '🚪 Log out',
    '🗑 Удалить аккаунт': '🗑 Delete account',
    'Неверный пароль': 'Wrong password',
    'заходил сегодня': 'played today',
    '☁ на сервере': '☁ on the server',

    // ---------- профиль ----------
    '🖼 КАРТИНКА ПРОФИЛЯ': '🖼 PROFILE PICTURE',
    '✏️ КАК ВАС ЗОВУТ': '✏️ YOUR NAME',
    '🎨 ЦВЕТ ИМЕНИ И ЧАТА': '🎨 NAME AND CHAT COLOUR',
    '📖 О СЕБЕ': '📖 ABOUT YOU',
    '📸 СНИМКИ ИЗ ИГРЫ': '📸 SCREENSHOTS',
    '📁 Выбрать картинку': '📁 Choose a picture',
    '📸 Снимок из игры': '📸 Take a screenshot',
    '✖ Убрать картинку': '✖ Remove picture',
    '💾 Сохранить рассказ': '💾 Save your story',
    '📁 Добавить картинку в снимки': '📁 Add a picture to screenshots',
    'Пока ни одного снимка': 'No screenshots yet',
    'Золотой': 'Gold', 'Мятный': 'Mint', 'Небесный': 'Sky', 'Розовый': 'Pink',
    'Сиреневый': 'Lilac', 'Коралловый': 'Coral', 'Лаймовый': 'Lime', 'Ледяной': 'Ice',

    // ---------- настройки ----------
    'ЗВУК': 'SOUND',
    'КАРТИНКА': 'GRAPHICS',
    'УПРАВЛЕНИЕ КАМЕРОЙ': 'CAMERA',
    'Громкость музыки': 'Music volume',
    'Громкость звуков': 'Sound volume',
    'Чувствительность мыши': 'Mouse sensitivity',
    'Язык': 'Language',
    'ЯЗЫК': 'LANGUAGE',
    'Русский': 'Russian',

    // ---------- частые сообщения ----------
    'Не хватает монет': 'Not enough coins',
    'Уже куплено': 'Already bought',
    'Сохранено': 'Saved',
    'Прогресс сброшен': 'Progress reset',
    'Эта локация вам ещё не открыта': 'This location is not unlocked yet',
    'Сервер не подключён': 'Not connected to a server',
    'Нет связи с сервером': 'No connection to the server',
    'Ищем сервер…': 'Looking for a server…',
    'Подключаемся к серверу…': 'Connecting to the server…',
    'Связь с сервером потеряна': 'Lost connection to the server',
    'Пока никого. Позовите друга — меню «🎮 Играть вдвоём».':
      'Nobody here yet. Invite a friend from “🎮 Play together”.',
    'Друзей пока нет. Загляните во вкладку «Кто играет» или добавьте по нику.':
      'No friends yet. Check “Who is playing” or add someone by nickname.',
    'Вы играете без аккаунта': 'You are playing without an account',

    // ---------- команды ----------
    '🛡 Это база чужой команды — туда нельзя':
      '🛡 This is the other team’s base — you cannot go there',
    '🐾 Кот вернулся в бой': '🐾 Your cat is back in the fight',
    '😿 Кота одолели — возвращаемся на базу…':
      '😿 Your cat was beaten — heading back to base…',

    // ---------- выходки ----------
    'Танец': 'Dance', 'Привет!': 'Hello!', 'Поклон': 'Bow',
    'Умывается': 'Washing', 'Потянуться': 'Stretch', 'Ура!': 'Hooray!',
    'Полежать': 'Lie down', 'Испугался': 'Startled', 'Задумался': 'Thinking',
    'Кувырок': 'Roll over', 'Мурлыкать': 'Purring', 'Дразнится': 'Teasing',
    'Спать': 'Sleep', 'Прыгать': 'Bounce', 'Сидеть': 'Sit', 'Смеётся': 'Laughing',
    'Грустит': 'Sad', 'Сердится': 'Angry', 'Крадётся': 'Sneaking',
    'Валяется': 'Rolling about', 'Колдует': 'Casting', 'Бодается': 'Head bump',
    'Чихает': 'Sneezing', 'Гордится': 'Proud',
    'Türkçe': 'Turkish',

    // ---------- подписи языков ----------
    'полностью': 'complete',
    'интерфейс': 'interface',
    'скоро': 'coming soon',
    'Қазақша': 'Kazakh',
    'Українська': 'Ukrainian',
    'Игра сама выбирает язык вашего устройства при первом запуске. Русский переведён полностью — он родной. Английский покрывает интерфейс: непереведённые места останутся русскими, и это видно честно. Казахский и украинский пока ждут перевода.':
      'The game picks your device language on first launch. Russian is complete — ' +
      'it is the original. English covers the interface: anything not translated yet ' +
      'stays in Russian, so you can see honestly what is left. Kazakh and Ukrainian ' +
      'are still waiting for a translation.'
  });
})(this);
