/**
 * ТУРЕЦКИЙ ПЕРЕВОД
 *
 * Слева — фраза как она написана в игре, справа — перевод.
 * Фразы, которых тут нет, останутся русскими: так честно видно,
 * что ещё предстоит перевести.
 */
(function (global) {
  'use strict';
  const KM = global.KM;

  KM.I18N.add('tr', {
    // ---------- главное меню ----------
    '▶ ИГРАТЬ': '▶ OYNA',
    '🛒 Магазин': '🛒 Dükkân',
    '🎰 Колесо и сундуки': '🎰 Çark ve sandıklar',
    '🐾 Питомцы': '🐾 Evcil hayvanlar',
    '⭐ Навыки': '⭐ Yetenekler',
    '🐱 Коты': '🐱 Kediler',
    '🎒 Сумка': '🎒 Çanta',
    '⚙ Настройки': '⚙ Ayarlar',
    '❔ Управление': '❔ Kontroller',
    '💾 Мои игры': '💾 Oyunlarım',
    '🎮 Играть вдвоём': '🎮 Birlikte oyna',
    '🌍 Сервера': '🌍 Sunucular',
    '🌐 Друзья': '🌐 Arkadaşlar',
    '👤 Профиль': '👤 Profil',
    '🎨 Изменить профиль': '🎨 Profili düzenle',

    // ---------- общие кнопки ----------
    '← Назад': '← Geri',
    'Назад': 'Geri',
    'Отмена': 'Vazgeç',
    'Хорошо': 'Tamam',
    'Готово': 'Bitti',
    'Сохранить': 'Kaydet',
    'Дальше': 'İleri',
    'Войти': 'Giriş yap',
    'Продолжить': 'Devam et',
    '▶ Продолжить': '▶ Devam et',
    'Выйти': 'Çıkış yap',
    'Удалить': 'Sil',
    'Убрать': 'Kaldır',
    'Закрыть': 'Kapat',
    'Купить': 'Satın al',
    'Надеть': 'Giy',
    'Снять': 'Çıkar',
    'Выбрать': 'Seç',
    'Играть': 'Oyna',
    'Ещё раз': 'Tekrar',
    'В меню': 'Ana menü',

    // ---------- экраны ----------
    'ЛОКАЦИИ': 'BÖLGELER',
    'МАГАЗИН': 'DÜKKÂN',
    'ПИТОМЦЫ': 'EVCİL HAYVANLAR',
    'НАВЫКИ': 'YETENEKLER',
    'КОТЫ': 'KEDİLER',
    'СУМКА': 'ÇANTA',
    'НАСТРОЙКИ': 'AYARLAR',
    'УПРАВЛЕНИЕ': 'KONTROLLER',
    'ПАУЗА': 'DURAKLATILDI',
    'ПРОФИЛЬ': 'PROFİL',
    '👤 ПРОФИЛЬ': '👤 PROFİL',
    '🎨 МОЙ ПРОФИЛЬ': '🎨 PROFİLİM',
    '🌍 СЕРВЕРА': '🌍 SUNUCULAR',
    '🌐 СЕРВЕР': '🌐 SUNUCU',
    '✉ ПЕРЕПИСКА': '✉ MESAJLAR',
    '💾 МОИ ИГРЫ': '💾 OYUNLARIM',
    '🎰 КОЛЕСО И СУНДУКИ': '🎰 ÇARK VE SANDIKLAR',
    '🎮 ИГРАТЬ ВДВОЁМ': '🎮 BİRLİKTE OYNA',

    // ---------- игра ----------
    'Играть одному': 'Tek başına oyna',
    'Тихо, спокойно и без интернета. Обычная сложность.':
      'Sakin, huzurlu ve internetsiz. Normal zorluk.',
    'ИГРАТЬ ВМЕСТЕ': 'BİRLİKTE OYNA',
    'ИЛИ САМОМУ': 'YA DA TEK BAŞINA',
    'ИЛИ': 'YA DA',
    'Игра на сервере': 'Sunucuda oyun',
    'Дружная охота': 'Dostça av',
    'Красные против синих': 'Kırmızılar mavilere karşı',
    'Battle: один победитель': 'Battle: tek kazanan',
    'Мирный': 'Barışçıl',
    'Здоровье': 'Can',
    'Мана': 'Mana',
    'Уровень': 'Seviye',
    'Опыт': 'Tecrübe',
    'Монеты': 'Altın',
    'Пауза (Esc)': 'Duraklat (Esc)',
    'Сумка (I)': 'Çanta (I)',
    'Кто играет': 'Kimler oynuyor',
    'Победа!': 'Kazandın!',
    'Кот сомлел': 'Kedin bayıldı',
    'ПОБЕДА': 'ZAFER',

    // ---------- сервера ----------
    'ОТКРЫТЫ ВСЕМ': 'HERKESE AÇIK',
    'СЕРВЕРА ИГРОКОВ': 'OYUNCU SUNUCULARI',
    '✨ Создать свой сервер': '✨ Kendi sunucunu kur',
    '✨ Открыть свой сервер здесь': '✨ Burada kendi sunucunu aç',
    '▶ Играть здесь': '▶ Burada oyna',
    '← К выбору режима': '← Mod seçimine dön',
    'ВАШ СОБСТВЕННЫЙ СЕРВЕР': 'KENDİ SUNUCUN',
    'ВО ЧТО ИГРАЕМ': 'NE OYNUYORUZ',
    'ГДЕ': 'NEREDE',
    'КОГО ПУСКАТЬ': 'KİMLER GİREBİLİR',
    'Всех подряд': 'Herkes',
    'Только друзей': 'Sadece arkadaşlar',
    'По слову-ключу': 'Parola ile',
    'Название': 'Ad',
    'Локация': 'Bölge',
    'Мест': 'Kişi sayısı',
    'Подпись': 'Kısa not',
    'Слово-ключ': 'Parola',
    'В списке': 'Listede',
    '👁 Показывать всем': '👁 Herkese göster',
    '🙈 Не показывать': '🙈 Gizli tut',
    '🚀 Открыть сервер': '🚀 Sunucuyu aç',
    '← К списку': '← Listeye dön',
    '👑 ВАШ СЕРВЕР': '👑 SENİN SUNUCUN',
    '📨 Позвать': '📨 Davet et',
    'уже тут': 'zaten burada',
    'попросить уйти': 'gitmesini iste',
    'в друзья': 'arkadaş ekle',
    '🏠 Поискать по всей домашней сети': '🏠 Tüm ev ağını tara',
    '🔌 Искать сервера': '🔌 Sunucu ara',
    '🔌 Попробовать снова': '🔌 Tekrar dene',
    'Вписать адрес вручную': 'Adresi elle gir',
    'Адрес': 'Adres',
    'КУДА ИГРА СТУЧАЛАСЬ': 'OYUN NERELERİ DENEDİ',
    '📂 ИГРА ОТКРЫТА ИЗ ФАЙЛА': '📂 OYUN DOSYADAN AÇILDI',
    '🚀 Открыть с компьютера': '🚀 Bilgisayardan aç',
    '📋 Скопировать': '📋 Kopyala',
    '📱 ИГРАТЬ С ТЕЛЕФОНА': '📱 TELEFONDAN OYNA',
    'Домашний компьютер': 'Ev bilgisayarı',
    'Этот компьютер': 'Bu bilgisayar',
    'Этот сайт': 'Bu site',
    'Ваш адрес': 'Senin adresin',
    'вы тут': 'buradasın',

    // ---------- друзья и чат ----------
    '👥 Кто играет': '👥 Kimler oynuyor',
    '🐾 Друзья': '🐾 Arkadaşlar',
    '➕ Добавить': '➕ Ekle',
    'ДРУЗЬЯ': 'ARKADAŞLAR',
    'ЗАЯВКИ В ДРУЗЬЯ': 'ARKADAŞLIK İSTEKLERİ',
    'Ник': 'Takma ad',
    'Ник друга': 'Arkadaşının takma adı',
    'ник друга': 'arkadaşının takma adı',
    'начните вводить ник': 'takma adı yazmaya başla',
    '✔ Принять': '✔ Kabul et',
    '🐾 друг': '🐾 arkadaş',
    '● в игре': '● oyunda',
    '📨 Позвать сюда': '📨 Buraya çağır',
    '🌍 К нему': '🌍 Yanına git',
    'написать другу…': 'arkadaşına yaz…',
    'Тут пока пусто. Напишите первое письмо 🐾':
      'Burası henüz boş. İlk mesajı sen yaz 🐾',
    'не в игре': 'oyunda değil',
    'в игре': 'oyunda',
    '👥 КТО ИГРАЕТ': '👥 KİMLER OYNUYOR',

    // ---------- аккаунт ----------
    'АККАУНТ НА СЕРВЕРЕ': 'SUNUCU HESABI',
    '🔑 Войти': '🔑 Giriş yap',
    '✨ Завести новый': '✨ Yeni hesap aç',
    '✨ Создать новый аккаунт': '✨ Yeni hesap oluştur',
    '🐾 Завести аккаунт': '🐾 Hesap oluştur',
    '🔑 У меня уже есть': '🔑 Zaten hesabım var',
    'Пароль': 'Parola',
    'пароль': 'parola',
    'ваш ник на сервере': 'sunucudaki takma adın',
    'Имя': 'İsim',
    'НА ЧЁМ ИГРАЕТЕ': 'NEYLE OYNUYORSUN',
    'Компьютер': 'Bilgisayar',
    'Планшет': 'Tablet',
    'Телефон': 'Telefon',
    'ДЕЙСТВИЯ': 'İŞLEMLER',
    '🔑 Сменить пароль': '🔑 Parolayı değiştir',
    '🔄 Другой аккаунт': '🔄 Başka hesap',
    '🚪 Выйти из аккаунта': '🚪 Hesaptan çık',
    '🗑 Удалить аккаунт': '🗑 Hesabı sil',
    'Неверный пароль': 'Parola yanlış',
    'заходил сегодня': 'bugün oynadı',
    '☁ на сервере': '☁ sunucuda',

    // ---------- профиль ----------
    '🖼 КАРТИНКА ПРОФИЛЯ': '🖼 PROFİL RESMİ',
    '✏️ КАК ВАС ЗОВУТ': '✏️ ADIN NE',
    '🎨 ЦВЕТ ИМЕНИ И ЧАТА': '🎨 İSİM VE SOHBET RENGİ',
    '📖 О СЕБЕ': '📖 HAKKINDA',
    '📸 СНИМКИ ИЗ ИГРЫ': '📸 OYUN KARELERİ',
    '📁 Выбрать картинку': '📁 Resim seç',
    '📸 Снимок из игры': '📸 Oyundan kare al',
    '✖ Убрать картинку': '✖ Resmi kaldır',
    '💾 Сохранить рассказ': '💾 Yazını kaydet',
    '📁 Добавить картинку в снимки': '📁 Karelere resim ekle',
    'Пока ни одного снимка': 'Henüz hiç kare yok',
    'Золотой': 'Altın', 'Мятный': 'Nane', 'Небесный': 'Gök', 'Розовый': 'Pembe',
    'Сиреневый': 'Leylak', 'Коралловый': 'Mercan', 'Лаймовый': 'Misket limonu',
    'Ледяной': 'Buz',

    // ---------- настройки ----------
    'ЗВУК': 'SES',
    'КАРТИНКА': 'GÖRÜNTÜ',
    'УПРАВЛЕНИЕ КАМЕРОЙ': 'KAMERA',
    'Громкость музыки': 'Müzik sesi',
    'Громкость звуков': 'Efekt sesi',
    'Чувствительность мыши': 'Fare hassasiyeti',
    'Язык': 'Dil',
    'ЯЗЫК': 'DİL',
    'Русский': 'Rusça',

    // ---------- подписи языков ----------
    'полностью': 'tamamı',
    'интерфейс': 'arayüz',
    'скоро': 'yakında',
    'Қазақша': 'Kazakça',
    'Українська': 'Ukraynaca',

    // ---------- частые сообщения ----------
    'Не хватает монет': 'Altının yetmiyor',
    'Уже куплено': 'Zaten satın alındı',
    'Сохранено': 'Kaydedildi',
    'Прогресс сброшен': 'İlerleme sıfırlandı',
    'Эта локация вам ещё не открыта': 'Bu bölge henüz açılmadı',
    'Сервер не подключён': 'Sunucuya bağlı değil',
    'Нет связи с сервером': 'Sunucuyla bağlantı yok',
    'Ищем сервер…': 'Sunucu aranıyor…',
    'Подключаемся к серверу…': 'Sunucuya bağlanılıyor…',
    'Связь с сервером потеряна': 'Sunucu bağlantısı koptu',
    'Вы играете без аккаунта': 'Hesapsız oynuyorsun',
    'Пока никого. Позовите друга — меню «🎮 Играть вдвоём».':
      'Henüz kimse yok. “🎮 Birlikte oyna” menüsünden bir arkadaşını çağır.',
    'Друзей пока нет. Загляните во вкладку «Кто играет» или добавьте по нику.':
      'Henüz arkadaşın yok. “Kimler oynuyor” sekmesine bak ya da takma adla ekle.',

    // ---------- команды ----------
    '🛡 Это база чужой команды — туда нельзя':
      '🛡 Burası rakip takımın üssü — giremezsin',
    '🐾 Кот вернулся в бой': '🐾 Kedin savaşa döndü',
    '😿 Кота одолели — возвращаемся на базу…':
      '😿 Kedin yenildi — üsse dönüyoruz…',

    // ---------- выходки ----------
    'Танец': 'Dans', 'Привет!': 'Merhaba!', 'Поклон': 'Selam ver',
    'Умывается': 'Yıkanıyor', 'Потянуться': 'Gerin', 'Ура!': 'Yaşasın!',
    'Полежать': 'Uzan', 'Испугался': 'Korktu', 'Задумался': 'Düşünüyor',
    'Кувырок': 'Takla', 'Мурлыкать': 'Mırlıyor', 'Дразнится': 'Dalga geçiyor',
    'Спать': 'Uyu', 'Прыгать': 'Zıpla', 'Сидеть': 'Otur', 'Смеётся': 'Gülüyor',
    'Грустит': 'Üzgün', 'Сердится': 'Kızgın', 'Крадётся': 'Sinsice yürüyor',
    'Валяется': 'Yuvarlanıyor', 'Колдует': 'Büyü yapıyor', 'Бодается': 'Kafa atıyor',
    'Чихает': 'Hapşırıyor', 'Гордится': 'Gururlu'
  });
})(this);
